(() => {
  if (location.pathname !== "/dashboard.html") return;
  let pix={key:"",keyType:"",receiver:"",city:"",description:""}; let loaded=false;
  function qrUrl(code){return"https://quickchart.io/qr?size=320&margin=2&ecLevel=M&text="+encodeURIComponent(code||"")}
  async function carregarPix(){if(loaded)return;try{const r=await fetch("/api/settings/public",{cache:"no-store"});const d=await r.json();const s=d.settings||{};pix={key:s.pix_key||"",keyType:s.pix_key_type||"",receiver:s.pix_receiver_name||"MyBets",city:s.pix_city||"Brasilia",description:s.pix_description||"MyBets"};loaded=true}catch(_){} }
  function abrir(){let modal=document.getElementById("depositPixModal");if(!modal){modal=document.createElement("div");modal.id="depositPixModal";modal.style.cssText="position:fixed;inset:0;z-index:1000;display:flex;align-items:center;justify-content:center;padding:12px;background:rgba(0,0,0,.86);overflow:auto";modal.innerHTML=`<div style="width:min(560px,100%);max-height:94vh;overflow:auto;padding:20px 15px;border-radius:22px;background:#0b1119;border:1px solid rgba(245,197,66,.25);box-shadow:0 20px 60px rgba(0,0,0,.6);color:#fff;text-align:center"><button id="depositPixClose" style="float:right;width:44px;height:44px;border:0;border-radius:13px;background:#151d27;color:#fff;font-size:28px">×</button><h2 style="margin:5px 45px 5px;color:#ffdc60;font-size:27px">💰 Depositar via Pix</h2><p style="color:#aeb5c2;margin:0 0 14px">Escolha o valor diretamente no seu banco e faça o Pix usando o QR Code ou a chave abaixo.</p><div style="background:#fff;border-radius:16px;padding:10px;width:250px;height:250px;margin:0 auto"><img id="depositQr" alt="QR Code da chave Pix" style="width:100%;height:100%;display:block"></div><div id="depositPixKeyDisplay" style="margin:12px 0 0;padding:12px;border-radius:12px;background:#121923;color:#fff;font-weight:800;word-break:break-all;font-size:14px"></div><div style="text-align:left;margin-top:13px;padding:12px;border-radius:12px;background:#121923;color:#aeb5c2;font-size:13px;line-height:1.5">💡 <strong style="color:#fff">O valor não é informado aqui.</strong><br>Digite no aplicativo do seu banco o valor que deseja enviar. Depois que o Pix for concluído, volte aqui e solicite a conferência. O administrador irá conferir o valor realmente recebido no extrato e liberar o saldo.</div><button id="copyPixCode" style="width:100%;height:48px;margin-top:13px;border:1px solid rgba(245,197,66,.5);border-radius:13px;background:#151d27;color:#fff;font-weight:900">📋 COPIAR CHAVE PIX</button><button id="sendDeposit" style="width:100%;height:50px;margin-top:10px;border:0;border-radius:13px;background:linear-gradient(180deg,#ffe47b,#e0a51a);color:#07090d;font-weight:900">JÁ ENVIEI — SOLICITAR CONFERÊNCIA</button><div id="depositPixMessage" style="min-height:24px;margin-top:10px;color:#ffcf3f;font-size:13px"></div><div style="text-align:left;margin-top:13px;padding:12px;border-radius:12px;background:#121923;color:#aeb5c2;font-size:12px;line-height:1.45">O saldo só será liberado após a conferência do administrador. O valor aprovado será exatamente o valor identificado pelo administrador no extrato.</div></div>`;document.body.appendChild(modal);document.getElementById("depositPixClose").onclick=()=>modal.remove();modal.addEventListener("click",e=>{if(e.target===modal)modal.remove()});document.getElementById("copyPixCode").onclick=copiar;document.getElementById("sendDeposit").onclick=enviar}
    modal.style.display="flex";carregarPix().then(atualizar);atualizar();
  }
  function atualizar(){const img=document.getElementById("depositQr"),keyDisplay=document.getElementById("depositPixKeyDisplay");if(!img)return;const key=String(pix.key||"").trim();if(keyDisplay)keyDisplay.textContent=key||"Chave Pix não configurada";img.src=key?qrUrl(key):"";img.style.opacity=key?"1":".45";img.dataset.pixKey=key}
  async function copiar(){const key=document.getElementById("depositQr")?.dataset.pixKey||String(pix.key||"").trim(),msg=document.getElementById("depositPixMessage");if(!key){if(msg)msg.textContent="A chave Pix ainda não está configurada.";return}try{await navigator.clipboard.writeText(key);if(msg)msg.textContent="✅ Chave Pix copiada."}catch(_){if(msg)msg.textContent="Não foi possível copiar automaticamente."}}
  async function enviar(){const msg=document.getElementById("depositPixMessage");const userId=Number(localStorage.getItem("userId")||sessionStorage.getItem("userId")||window.currentUser?.id||window.user?.id||0);if(!Number.isInteger(userId)||userId<=0){if(msg)msg.textContent="Sessão do jogador não identificada. Faça login novamente.";return}const button=document.getElementById("sendDeposit");if(button)button.disabled=true;if(msg)msg.textContent="Registrando sua solicitação...";try{const r=await fetch("/api/deposits",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId,amount:0,playerNote:"Valor não informado pelo jogador; será conferido pelo administrador no extrato Pix."})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.message||"Não foi possível registrar o pedido de depósito.");if(msg)msg.textContent="✅ Solicitação enviada. O administrador irá conferir o valor recebido no extrato Pix.";setTimeout(()=>{const modal=document.getElementById("depositPixModal");if(modal)modal.remove()},1400)}catch(e){if(msg)msg.textContent="❌ "+(e.message||"Não foi possível registrar o pedido.");if(button)button.disabled=false}}
  window.openDeposit=abrir;
})();
