const API = "/api";
let jogos = [
  {id:"fortune7",name:"Fortune 7",type:"slot",description:"Caça-níqueis clássico MyBets."},
  {id:"diamondGold",name:"Diamond Gold",type:"slot",description:"Diamantes e grandes combinações."},
  {id:"royalJackpot",name:"Royal Jackpot",type:"slot",description:"Tema premium MyBets."},
  {id:"lucky7",name:"Lucky 7",type:"slot",description:"O clássico 7 em uma rodada rápida."},
  {id:"roulette",name:"Roleta",type:"roulette",description:"Roleta única de 16 fatias."}
];
let jogoAtual=null,slotBet=1,rouletteBet=.5,slotSpinning=false,rouletteSpinning=false;
const THEMES={
 fortune7:{title:"FORTUNE 7",accent:"#d51f3d",symbols:["7","🍒","🍋","🔔","BAR","💎","⭐"]},
 diamondGold:{title:"DIAMOND GOLD",accent:"#178fca",symbols:["💎","👑","🪙","7","💠","✨"]},
 royalJackpot:{title:"ROYAL JACKPOT",accent:"#9a55d8",symbols:["👑","💎","7","💰","♛","✨"]},
 lucky7:{title:"LUCKY 7",accent:"#e3a51b",symbols:["7","🍒","🍀","BAR","⭐","🔔"]}
};
const $=id=>document.getElementById(id);
function usuario(){try{return JSON.parse(localStorage.getItem("jpbet_user")||"null")}catch(_){return null}}
function uid(){const u=usuario();return u?.id??u?.userId??null}
function moeda(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function toast(m){const e=$("toast");if(!e)return;e.textContent=m;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),2600)}
function saldo(v){const n=Number(v||0);[$("balance"),$("stageBalance")].forEach(e=>{if(e)e.textContent=n.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})});const u=usuario();if(u){u.balance=n;localStorage.setItem("jpbet_user",JSON.stringify(u))}}
async function conta(){const id=uid();if(!id)return null;const r=await fetch(`${API}/account/${id}`);const d=await r.json();if(!r.ok||!d.ok)throw Error(d.message||"Erro ao consultar saldo.");saldo(d.user.balance);return d.user}
function renderJogos(){const b=$("gamesContainer");if(!b)return;const m=$("gamesMessage");if(m)m.style.display="none";b.innerHTML=jogos.map(j=>`<article class="lobby-card"><div class="lobby-icon">${j.type==="roulette"?"🎡":j.id==="diamondGold"?"💎":j.id==="royalJackpot"?"👑":j.id==="lucky7"?"🍀":"🎰"}</div><h3>${j.name}</h3><p>${j.description}</p><button class="lobby-play" type="button" data-game="${j.id}">JOGAR</button></article>`).join("");b.querySelectorAll("[data-game]").forEach(x=>x.onclick=()=>abrir(x.dataset.game))}
function abrir(id){jogoAtual=jogos.find(j=>j.id===id);if(!jogoAtual)return;$("gamesLobby").hidden=true;$("gameStage").hidden=false;$("gameTitle").textContent=jogoAtual.name;conta().catch(()=>{});jogoAtual.type==="roulette"?roletaUI():slotUI()}
function voltar(){$("gameStage").hidden=true;$("gamesLobby").hidden=false;jogoAtual=null}
function slotUI(){const t=THEMES[jogoAtual.id]||THEMES.fortune7;$("gameTypeLabel").textContent="SLOT";$("slotPanel").hidden=false;$("roulettePanel").hidden=true;$("marqueeTitle").textContent=t.title;$("slotBetValue").textContent=moeda(slotBet);$("slotStatus").textContent="Boa sorte!";$("winDisplay").textContent="R$ 0,00";$("screenWin").textContent="R$ 0,00";document.documentElement.style.setProperty("--slot1",t.accent);reels()}
function reels(){const s=(THEMES[jogoAtual.id]||THEMES.fortune7).symbols;[0,1,2].forEach(i=>{const r=$("reel"+i);if(!r)return;r.innerHTML="";for(let n=0;n<3;n++){const e=document.createElement("div");e.className="reel-symbol";e.textContent=s[(i+n)%s.length];r.appendChild(e)}})}
function mostrarReels(mult){const s=(THEMES[jogoAtual.id]||THEMES.fortune7).symbols;const v=mult>=10?s[0]:mult>=5?s[1]||s[0]:mult>=3?s[2]||s[0]:mult>=2?s[0]:s[Math.floor(Math.random()*s.length)];[0,1,2].forEach(i=>{const r=$("reel"+i);if(r)r.innerHTML=`<div class="reel-symbol">${v}</div>`})}
async function slotSpin(){if(slotSpinning)return;const id=uid();if(!id)return toast("Faça login para jogar.");slotSpinning=true;const b=$("slotSpinButton");if(b)b.disabled=true;$("slotStatus").textContent="Girando...";try{const r=await fetch(`${API}/roulette/spin`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:id,betAmount:slotBet,betType:"roulette",rouletteId:"sorte"})});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.message||"Não foi possível girar o slot.");const p=Number(d.spin?.prize||0),m=Number(d.spin?.multiplier||0);mostrarReels(m);$("screenWin").textContent=moeda(p);$("winDisplay").textContent=moeda(p);$("slotStatus").textContent=p>0?`Prêmio: ${moeda(p)}`:"Rodada concluída.";saldo(d.user?.balance)}catch(e){toast(e.message)}finally{slotSpinning=false;if(b)b.disabled=false}}
function slotBetSet(v){slotBet=Math.max(1,Math.min(100,Number(v)));$("slotBetValue").textContent=moeda(slotBet)}
function roletaUI(){$("gameTypeLabel").textContent="RODA DA SORTE";$("slotPanel").hidden=true;$("roulettePanel").hidden=false;$("rouletteBetValue").textContent=moeda(rouletteBet);criarRoleta()}
function criarRoleta(){const w=$("rouletteWheel");if(!w)return;const a=360/16,l=["","","5X","","","","10X","","","","2X","","","","3X",""];w.innerHTML="";l.forEach((x,i)=>{const e=document.createElement("span");e.className=`roulette-label ${x?"prize":"zero"}`;e.textContent=x;const m=i*a+a/2;e.style.transform=`translate(-50%,-50%) rotate(${m}deg) translateY(-38%) rotate(${-m}deg)`;w.appendChild(e)});w.style.background=`conic-gradient(from -${a/2}deg,${l.map((_,i)=>`${i%2?"#111":"#D4AF37"} ${i*a}deg ${(i+1)*a}deg`).join(",")})`}
async function rouletteSpin(){if(rouletteSpinning)return;const id=uid();if(!id)return toast("Faça login para jogar.");rouletteSpinning=true;const bs=[$("rouletteSpinButton"),$("rouletteHubButton")];bs.forEach(b=>{if(b)b.disabled=true});try{const r=await fetch(`${API}/roulette/spin`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:id,betAmount:rouletteBet,betType:"roulette",rouletteId:"sorte"})});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.message||"Não foi possível girar a roleta.");const idx=Number(d.spin?.index||0),p=Number(d.spin?.prize||0),m=Number(d.spin?.multiplier||0),w=$("rouletteWheel");if(w){const a=360/16;w.style.transition="transform 1.8s cubic-bezier(.12,.75,.18,1)";w.style.transform=`rotate(${360*5+(360-(idx*a+a/2))}deg)`}$("rouletteResult").textContent=p>0?`Resultado: ${m}X — prêmio ${moeda(p)}`:"Resultado: sem prêmio nesta rodada.";$("winDisplay").textContent=moeda(p);saldo(d.user?.balance)}catch(e){toast(e.message)}finally{rouletteSpinning=false;bs.forEach(b=>{if(b)b.disabled=false})}}
function eventos(){ $("backButton")?.addEventListener("click",()=>location.href="dashboard.html");$("stageBack")?.addEventListener("click",voltar);$("slotSpinButton")?.addEventListener("click",slotSpin);$("betMinus")?.addEventListener("click",()=>slotBetSet(slotBet-1));$("betPlus")?.addEventListener("click",()=>slotBetSet(slotBet+1));document.querySelectorAll("[data-bet]").forEach(b=>b.onclick=()=>slotBetSet(b.dataset.bet));$("rouletteSpinButton")?.addEventListener("click",rouletteSpin);$("rouletteHubButton")?.addEventListener("click",rouletteSpin);$("rouletteBetMinus")?.addEventListener("click",()=>{rouletteBet=Math.max(.5,rouletteBet-.5);$("rouletteBetValue").textContent=moeda(rouletteBet)});$("rouletteBetPlus")?.addEventListener("click",()=>{rouletteBet=Math.min(100,rouletteBet+.5);$("rouletteBetValue").textContent=moeda(rouletteBet)});document.querySelectorAll("[data-roulette-bet]").forEach(b=>b.onclick=()=>{rouletteBet=Number(b.dataset.rouletteBet);$("rouletteBetValue").textContent=moeda(rouletteBet)})}
document.addEventListener("DOMContentLoaded",()=>{eventos();renderJogos();conta().catch(()=>{});const id=new URLSearchParams(location.search).get("game");if(id)abrir(id)});
