import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";
import authRouter from "./auth.js";
import settingsRouter from "./settings.js";
import { pool } from "./db.js";
import { validarSessaoAdmin } from "./adminSession.js";
import { registrarAuditoria as registrarAuditoriaSistema } from "./audit.js";
import { enviarNotificacao } from "./notifications.js";
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
